### ISSUE TITLE
Using with ESP32

### ISSUE THREAD

**Issue by kisvegabor** [Samsung/thorvg#1014]
Hi,

Thanks for developing this full-featured library.

I'm thinking about porting ThorVG to an ESP32 module. The 2 problems I see are that ESP32 needs CMake to build and the compiled library should be in hundreds of kilobytes of magnitude. 

Do think it's feasible?

**Comment by hermet** [comment]
Hi, @kisvegabor thanks for reaching us. 

1. The best solution I'd like to recommend is to use meson build system as possible as you can. Otherwise we can branch out a cmake from the main stream branch then build the cmake build environment. In this scenario, we need to plan for that task completion from now. It will be great if you can contribute for thorvg otherwise we can compromise the schedule(expected date) for all of us. What date do you expect to use it?

2. The binary size of thorvg symbol will be less than 200kb. Currently its size is 157kb in Tizen system. Of course the binary is applied with --strip option.

3. Question: Do you have the main window/rendering system and you'd like to use the vector drawing feature with thorvg? If so it's good to go.

**Comment by kisvegabor** [comment]
At this moment I'm evaluating the possible SVG libs to be used in [LVGL](https://github.com/lvgl/lvgl) SVG support on ESP32 came up as a request from a customer. So I'm checking what SVG parser+renderer libs can we adopt which runs on ESP32 too.

BTW, we already use [Samsung's Rlottie library](https://docs.lvgl.io/master/libs/rlottie.html) which is great (It supports Cmake so it's easier to use in an embedded environment)

> The best solution I'd like to recommend is to use meson build system as possible as you can. 

Yes, it'd be great to use meson, but I need to do more research to see how can meson and CMake of ESP interact.

>  What date do you expect to use it?

It depends on the mentioned customer. I have some ideas in mind to use a simpler SVG lib first but it'd great to use this lib at the and as it seems quite complete and backed Samsung. :slightly_smiling_face: 

> The binary size of thorvg symbol is around 150kb if the binary is applied with the strip.

It's perfect even in an embedded environment.

> Do you have the main window/rendering system and you'd like to use the vector drawing feature with thorvg? If so it's good to go.

As I mentioned we would use it in LVGL. The rasterized images would be displayed as any normal image. I'm also thinking about making it possible to allow switching LVGL's SW renderer to an advanced vector renderer at some point.

**Comment by hermet** [comment]
@kisvegabor Thanks for your reply, It sounds like Thorvg is an optimal library for your project at this moment. It provides simple and easy interface for svg and vector primitives, it draws on the given buffer like rlottie using sw rasterizer and it's extending to support multiple backends. If you already integrated rlottie, I believe thorvg won't be any issued in your project. Also, Now thorvg has a plan to support lottie animation, (rlottie is not much maintained these days actually) in the end it would be efficient at the development for all of us.  You can replace the rlottie with thorvg later when it officially support it. Now the problem is cmake part. Basically, thorvg desires to keep the only one build system, meson. I believe forkers could customize the build system since thorvg can't satisfy with all the build system around the world. If you need it immediately, I'd like to suggest you to do it by your demand, otherwise, I will consider to support it soon in this month.

**Comment by kisvegabor** [comment]
>  Now thorvg has a plan to support lottie animation
>  it's on the extending to support multiple backends.

Both are fantastic news. :tada: 

> Now the problem is cmake part. 

I'm new to Meson and Ninja so I needed to educate myself a little to understand what their exact roles are. Now I have a better understanding of it and it seems to me all we need is an external meson cross-file similar to [this](https://stackoverflow.com/questions/64588046/about-meson-cross-file-and-stm32). After that, we can use Meson+Ninja to build a library file using the settings coming from the cross-file. Can you confirm this?

**Comment by hermet** [comment]
@kisvegabor also i need to figure out it :-)

**Comment by kisvegabor** [comment]
Okay, I'll get back to you if I have something :slightly_smiling_face:

**Comment by steprun** [comment]
Buildroot is easier building cmake

**Comment by hermet** [comment]
please reopen if you think it's still valid.
