### ISSUE TITLE
Thorvg crashing oddly with threads set to 0.

### ISSUE THREAD

**Issue by fire** [Samsung/thorvg#1208]
Posted a bug report with more information on Godot Engine's issue tracker. The bug is confusing.

https://github.com/godotengine/godot/pull/59583

**Comment by akien-mga** [comment]
To give some context, this might very well be only a downstream bug / a misuse of the thorvg API.

Godot imports SVG files using thorvg, and by default all asset imports are done each on their own thread, so we can import multi files in parallel (not so relevant for SVGs which are fast to import, but it's important for VRAM compression of raster images which is very slow). You can see the reference to `ThreadWorkPool` in the backtrace at https://github.com/godotengine/godot/pull/59583#issuecomment-1081612751

The thorvg engine is initialized once when registering the import plugin here:
https://github.com/godotengine/godot/blob/3b4e94c8b57908f61a9028f757b2f4f8edc8987b/modules/svg/register_types.cpp#L40-L43

And then used here:
https://github.com/godotengine/godot/blob/3b4e94c8b57908f61a9028f757b2f4f8edc8987b/modules/svg/image_loader_svg.cpp#L64-L133

I don't know if `0` was used for the thread count by design, or by oversight. https://github.com/godotengine/godot/pull/59583 sets it to `max_threads - 1` and that solves the issue (even setting it to `1` is sufficient).

But I suggested that @fire opens an issue upstream as it seems weird to me that thorvg would crash in this situation. If we do use max number of threads for thorvg's TaskScheduler, I wonder how it interacts with Godot's own thread pool. I don't know much about async programming myself so take the above with a grain of salt - there might be an obvious issue with how we do things, and the linked PR might be the correct solution.

**Comment by hermet** [comment]
@fire  @akien-mga It looks like a thread-safety issue. tvg is designed to share internal data-resource among canvas instances, its mechanism of the thread-safety is only considered for internal threads.

If godot calls tvg apis on multi-threads, could you please try the following api for each canvas instance?

canvas->mempool(tvg::MempoolPolicy::Individual);

Once that, the canvas instance would use its own instance-designated internal resource.

**Comment by fire** [comment]
In https://github.com/godotengine/godot/pull/59583 we set it to be 1. I'm not sure if `canvas->mempool(tvg::MempoolPolicy::Individual);` is necessary.
