### ISSUE TITLE
Stroke wrong display

### ISSUE THREAD

**Issue by JSUYA** [Samsung/thorvg#123]
test code
```c++
--- a/src/examples/Opacity.cpp
+++ b/src/examples/Opacity.cpp
@@ -52,6 +52,9 @@ void tvgDrawCmds(tvg::Canvas* canvas)
     shape3->cubicTo(cx - halfRadius, cy + radius, cx - radius, cy + halfRadius, cx - radius, cy);
     shape3->cubicTo(cx - radius, cy - halfRadius, cx - halfRadius, cy - radius, cx, cy - radius);
     shape3->fill(255, 0, 0, 255);
+
+    shape3->stroke(100);
+    shape3->stroke(255, 0, 0, 255);
     scene->push(move(shape3));
```
![image](https://user-images.githubusercontent.com/7413838/97541127-f99f6c00-1a07-11eb-8156-f7759fb9933a.png)

There is a problem with the top of red circle.

**Comment by mgrudzinska** [comment]
I think this is the expected behavior.

The fill itself draws correctly. After adding a stroke the 'problem' appears because we don't close it. If you add shape3->close(), the beginning and the end of the stroke will be joined together and you will get a smooth vertex.

Below I have drawn 4 separate cubic - as you can see the fill connects smoothly, while the strokes with the default cap do not connect.
If you change the stroke cap to Butt (shape-> stroke (tvg :: StrokeCap :: Butt)) you will get a stroke that looks like one whole.

Default cap:
![notIssue](https://user-images.githubusercontent.com/67589014/97581083-6dd01480-19f4-11eb-8e3f-ae9578840afb.PNG)

Butt cap:
![notIssueButt](https://user-images.githubusercontent.com/67589014/97581114-788aa980-19f4-11eb-84fa-425ca9f0efca.PNG)

The code:
    shape3a->moveTo(cx, cy - radius);
    shape3a->cubicTo(cx + halfRadius, cy - radius, cx + radius, cy - halfRadius, cx + radius, cy);

    shape3b->moveTo(cx + radius, cy);
    shape3b->cubicTo(cx + radius, cy + halfRadius, cx + halfRadius, cy + radius, cx, cy+ radius);

    shape3c->moveTo(cx, cy + radius);
    shape3c->cubicTo(cx - halfRadius, cy + radius, cx - radius, cy + halfRadius, cx - radius, cy);

    shape3d->moveTo(cx - radius, cy);
    shape3d->cubicTo(cx - radius, cy - halfRadius, cx - halfRadius, cy - radius, cx, cy - radius);

    shape3a->fill(255, 0, 0, 255);
    shape3b->fill(0, 255, 0, 255);
    shape3c->fill(0, 0, 255, 255);
    shape3d->fill(255, 0, 255, 255);

    shape3a->stroke(255, 0, 0, 255);
    shape3b->stroke(0, 255, 0, 255);
    shape3c->stroke(0, 0, 255, 255);
    shape3d->stroke(255, 0, 255, 255);

    shape3a->stroke(100);
    shape3b->stroke(100);
    shape3c->stroke(100);
    shape3d->stroke(100);

    shape3a->stroke(tvg::StrokeCap::Butt);
    shape3b->stroke(tvg::StrokeCap::Butt);
    shape3c->stroke(tvg::StrokeCap::Butt);
    shape3d->stroke(tvg::StrokeCap::Butt);

    scene->push(move(shape3a));
    scene->push(move(shape3b));
    scene->push(move(shape3c));
    scene->push(move(shape3d));

**Comment by JSUYA** [comment]
@mgrudzinska 
Thank you for your kind explanation. I have checked there are no problems. I will close this issue. :)
