### ISSUE TITLE
Introduce loader & saver

### ISSUE THREAD

**Issue by hermet** [Samsung/thorvg#311]
class TVG_EXPORT Loader
{
    static std::unique_ptr(Picture) load(const std::string& path) noexcept;                                         
    // we can unify Picture::load() methods here later.
};

class TVG_EXPORT Saver
{
    static Result save(unique_ptr(Paint) paint, const std::string& path, bool async) noexcept;
};

i.e)
tvg::Saver::save(move(shape), "test.tvg", true);
tvg::Saver::save(unique_ptr<Paint(shape->duplicate), "test.tvg", true);

auto picture = tvg::Loader::load("test.tvg");

**Comment by mmaciola** [comment]
Regarding the Loader:
Picture::Impl do not share Paint* outside the class and it is not obvious how to create new picture, parse tvg file into scene, put this scene into picture's paint and return the picture. 
What do you think about loading the .tvg file the same way the .svg file is loaded now?:
`auto picture = tvg::Picture::gen();
picture->load(EXAMPLE_DIR"/tvg_file.tvg");
canvas->push(move(picture));`
This is how [the current WIP version](https://github.com/mmaciola/thorvg/tree/sandbox/mmaciola%2Fbinary_storer_loader_single_file_2) loads files.

It is suggested to define the loader class in `thorvg.h`. What do you think about defining the tvgLoader in tvgTvgLoader.h file (so the same `svg`, `png` and `raw` does)?

**Comment by mgrudzinska** [comment]
@hermet so for now we coded the modules in a way the svg loader is coded and I wondered why you wanted to make it in a different way. This lead me to the question whether the svg loader is coded now in a safe way.

So as I understand, we are guaranteed, that the loading task is ended before the update starts, but the update is called after pushing an object into the Canvas. So if I want to load the svg file and save it in the TVG format, then I don't need to call the push function. So in some cases it may crash. Am I right? Is that the reason, why you want to change the architecture of the loaders?

**Comment by mgrudzinska** [comment]
To give you a big picture.
Let say I want to save a scene. I pass it to the saver - a completely separate module. I can get the scene's properties using getters. But the scene can have children. and I need to get their addresses somehow, so that I'll be able to use getters to know theirs properties. That's why I implement Iterators - now I'm able to iterate over all children of the scene.

https://github.com/Samsung/thorvg/pull/403


The other approach can be a serialize function. As I understand it could return already serialized properties of an object. But :
I need to implement the serialization in the corresponding class - like PictureImpl/SceneImpl/ShapeImpl - here I have all the access that I need. but - I don't like this sollution, because all the flags that loader understands and all the bytes count (after each flag a loader expects the information how many bytes there will come) are implemented in Pict,Shape,Scene and not in the saver module. So all what the saver does, is to call this serialize.

**Comment by mgrudzinska** [comment]
@hermet could you please take a look at these two patches ?
I'm not asking you to rev them, just take a look globally.

1) https://github.com/mgrudzinska/thorvg/tree/mgrudzinska/module_saver 
In this patch I introduce the `save` and the `serialize` APIs in the Paint class.
There is also the saver module implemented, but the main serialization takes place in the PaintImpl, SceneImpl, ShapeImpl and PictImpl, so I have direct access to all members and I can iterate over all nodes in a scene.

2) https://github.com/mgrudzinska/thorvg/tree/mgrudzinska/iterators_and_saver
Here, everything that is connected with saving is implemented in the `Saver` class.
I introduced `Iterator`s in the Paint class, since I need to iterate over all nodes of an object that is to be saved - the Saver class doesn't have direct access to the Impls.

Both of these approaches work but the second one doesn't support composition yet.

I think that I mixed two things here  - the saver from this issue and supporting the tvg format from the issue #375. 
I would really appreciate a comment on this subject.

**Comment by fire** [comment]
@mgrudzinska Do you think this project will make a SVG saver?

**Comment by mgrudzinska** [comment]
@hermet could you please answer this?

**Comment by hermet** [comment]
@mgrudzinska  @fire It will be very hard work. I don't know where it *practically needs it. Still ThorVG needs a lot of essential features. Thus right now we leave it just an open-task.  At least ThorVG can save to tvg & load it again.

**Comment by fire** [comment]
I agree about keeping SVG import open ended. There are a lot of SVG import tasks currently in the pipeline.

My end goal is a vector animation exporter, but I don't know how to achieve that.

**Comment by hermet** [comment]
@fire fyi, we gonna support both lottie & rive animation (by extension apis) in the next year.

**Comment by hermet** [comment]
Saver was introduced already but loader is not confirmed yet. Picture::load() is anyhow useful... do we really need separate Loader??
