### ISSUE TITLE
SVG Gradient Issue

### ISSUE THREAD

**Issue by hermet** [Samsung/thorvg#430]
"intertwingly.svg" in the thorvg examples doesn't show the gradient fill correctly. Need to investigate it.

**Comment by mgrudzinska** [comment]
I solved it by removing the whole part with usePercentage from the grad, but I want to double check it, since now tvg supports only `userSpaceOnUse`. the other value could be `objectBoundingBox` and it has to be added (that's why clipping in the #429 doesn't work). So some recalculations, like with the usePercentage, has to be done and that's why I don't want to push now a patch where I removed them.

**Comment by mgrudzinska** [comment]
it's partially solved in #514 - the rest of the differences in because tvg does not support fx and fy attributes

**Comment by hermet** [comment]
look good enough.
